import {
    AlarmSmokeIcon,
    AnvilIcon,
    AppleIcon,
    ArmchairIcon,
    AxeIcon,
    BabyIcon,
    BathIcon,
    BedDoubleIcon,
    BeefIcon,
    BeerIcon,
    BikeIcon,
    BlindsIcon,
    BlocksIcon,
    BookIcon,
    BriefcaseIcon,
    CctvIcon,
    ChefHatIcon,
    CloudIcon,
    CoffeeIcon,
    CookingPotIcon,
    CylinderIcon,
    DicesIcon,
    DonutIcon,
    FenceIcon,
    FlameIcon,
    FlameKindlingIcon,
    FootprintsIcon,
    Gamepad2Icon,
    GlassWaterIcon,
    Grid2X2Icon,
    HandPlatterIcon,
    HeaterIcon,
    KeyRoundIcon,
    LampCeilingIcon,
    LayoutGridIcon,
    LibraryIcon,
    LightbulbIcon,
    MapPinIcon,
    MartiniIcon,
    MonitorSmartphoneIcon,
    MountainSnowIcon,
    PawPrintIcon,
    PlugZapIcon,
    PopcornIcon,
    ProjectorIcon,
    RefreshCwIcon,
    ShirtIcon,
    ShoppingBasketIcon,
    ShowerHeadIcon,
    SpeakerIcon,
    SquareParkingIcon,
    TabletSmartphoneIcon,
    TvIcon,
    TvMinimalPlayIcon,
    UsersIcon,
    UtensilsIcon,
    WashingMachineIcon,
    WifiIcon,
    WineIcon,
} from "lucide-react";

export const CABIN_ICONS_MAP = {
    mapPin: <MapPinIcon />,
    refreshCw: <RefreshCwIcon />,
    users: <UsersIcon />,
    bedDouble: <BedDoubleIcon />,
    bath: <BathIcon />,
    chefHat: <ChefHatIcon />,
    cylinder: <CylinderIcon />,
    flame: <FlameIcon />,
    tv: <TvIcon />,
    wifi: <WifiIcon />,
    heater: <HeaterIcon />,
    utensils: <UtensilsIcon />,
    coffee: <CoffeeIcon />,
    wine: <WineIcon />,
    beef: <BeefIcon />,
    showerHead: <ShowerHeadIcon />,
    cloud: <CloudIcon />,
    lightbulb: <LightbulbIcon />,
    grid2x2: <Grid2X2Icon />,
    speaker: <SpeakerIcon />,
    popcorn: <PopcornIcon />,
    flameKindling: <FlameKindlingIcon />,
    blinds: <BlindsIcon />,
    washingMachine: <WashingMachineIcon />,
    shirt: <ShirtIcon />,
    dices: <DicesIcon />,
    library: <LibraryIcon />,
    monitorSmartphone: <MonitorSmartphoneIcon />,
    armchair: <ArmchairIcon />,
    mountainSnow: <MountainSnowIcon />,
    footprints: <FootprintsIcon />,
    fence: <FenceIcon />,
    pawPrint: <PawPrintIcon />,
    bike: <BikeIcon />,
    plugZap: <PlugZapIcon />,
    tabletSmartphone: <TabletSmartphoneIcon />,
    squareParking: <SquareParkingIcon />,
    cctv: <CctvIcon />,
    keyRound: <KeyRoundIcon />,
    tvMinimalPlay: <TvMinimalPlayIcon />,
    donut: <DonutIcon />,
    beer: <BeerIcon />,
    gamepad2: <Gamepad2Icon />,
    handPlatter: <HandPlatterIcon />,
    apple: <AppleIcon />,
    anvil: <AnvilIcon />,
    axe: <AxeIcon />,
    briefcaseMedical: <BriefcaseIcon />,
    alarmSmoke: <AlarmSmokeIcon />,
    baby: <BabyIcon />,
    blocks: <BlocksIcon />,
    projector: <ProjectorIcon />,
    shoppingBasket: <ShoppingBasketIcon />,
    lampCeiling: <LampCeilingIcon />,
    cookingPot: <CookingPotIcon />,
    glassWater: <GlassWaterIcon />,
    luggage: <LayoutGridIcon />,
    martini: <MartiniIcon />,
    book: <BookIcon />,
};
